/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */


INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id', 'test_project_id', 'test_domain_id', 'default', '测试Agent', '测试Agent描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":true,"rounds":3,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id2', 'test_project_id', 'test_domain_id','default', '测试Agent2', '测试Agent描述', 'data:image/png;base64,123', NULL, '[{"trigger_id":"test_trigger_id","name":"触发器1","type":"TIMER","cron":"0/10 * * * * ?","prompt":"打车"}]', NULL, NULL, '{"enable":true,"rounds":1,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id3', 'test_project_id', 'test_domain_id', 'default', '测试Agent3', '测试Agent描述', 'data:image/png;base64,123', NULL, '[{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 15:59:24"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 15:59:56"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:05"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:06"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:06"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:08"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:09"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:10"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:11"},{"trigger_id":"","name":"事件触发器1","type":"EVENT","cron":"0/10 * * * * ?","prompt":"预定会议2","params":[{"name":"location","description":"地点"}],"hook_url":"test_url","created_on":"2025-03-22 16:00:12"}]', NULL, NULL, '{"enable":false,"rounds":1,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id4', 'test_project_id', 'test_domain_id', 'default', '测试Agent4', '测试Agent描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":false,"rounds":1,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id5', 'test_project_id', 'test_domain_id', 'default', 'agent', '测试Agent描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":true,"rounds":3,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id6', 'test_project_id', 'test_domain_id', 'default', '', '测试描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":true,"rounds":3,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id,  domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id7', 'test_project_id', 'test_domain_id', 'default', '', '测试描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":true,"rounds":3,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id,  workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id8', 'test_project_id',  'test_domain_id','default', 'app', '测试Agent描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":true,"rounds":3,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);

INSERT
 INTO t_agent(agent_id, project_id,  domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, type, dsl_path, deleted)
VALUES ('test_agent_id9', 'test_project_id', 'test_domain_id', 'default', 'test_multi_agent', '测试Agent描述', 'data:image/png;base64,123', NULL, NULL, NULL, NULL, '{"enable":true,"rounds":3,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 'controller', 'agent/flow/test_agent_id9.json', 0);

INSERT
 INTO t_agent(agent_id, project_id, domain_id, workspace_id, name, description, icon, instructions, trigger_list, prologue, suggest_queries, additional_questions_config, status, creator, creator_id, created_on, updated_on, published_on, model_config, deleted)
VALUES ('test_agent_id10', 'test_project_id', 'test_domain_id', 'default', '测试Agent2', '测试Agent描述', 'data:image/png;base64,123', NULL, '[{"trigger_id":"test_trigger_id2","name":"触发器1","type":"TIMER","cron":"0/10 * * * * ?","prompt":"打车"}]', NULL, NULL, '{"enable":true,"rounds":1,"prompt":"1. 每次生成的问题不超过30个字。\n2. 生成问题的对话风格，与用户对话历史要一致，贴合用户对话场景。\n3. 不要生成相同或过于相似的问题。"}', 'published', 'test_creator', 'test_creator_id', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '2024-08-12 20:34:00', '{"top_p":0.5,"temperature":0.5}', 0);
