/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 */


INSERT  INTO t_user_model_service_provider (ID, PROVIDER_NAME, PROVIDER_NAME_EN, DESCRIPTION, TAGS, PROVIDER_URL, CREATED_DATE, LAST_UPDATED_DATE, LOGO, STATUS, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, IDENTITY_ID)
 VALUES ('model_test_provider', 'model_test_provider', 'model_test_provider', '', NULL, '', 1754668644437, 1754668644437, 'data:image=', 'created', '0', 'test_project_id', 'default', '2', '2', 'model_test_provider');

INSERT  INTO t_provider_auth_metadata (ID, PROVIDER_ID, AUTH_TYPE, AUTH_INFO, AUTH_URL, CREATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, IDENTITY_ID)
VALUES ('model_test_provider_mm', 'model_test_provider', 'API_KEY', '{"API Key":""}', '', '2', 1754668644437, 1754668644437, '0', 'test_project_id', 'default', '070ad379');

INSERT  INTO t_provider_auth_info (ID, PROVIDER_ID, AUTH_METADATA_ID, AUTH_TYPE, AUTH_INFO, CREATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, IDENTITY_ID)
VALUES ('model_test_provider_aa', 'model_test_provider', 'model_test_provider_mm', 'NO_AUTH', '{}', '2', 1754964550955, 1754964550955, '0', 'test_project_id', 'default', 'df1a716a');

INSERT  INTO t_model_service (ID, PROVIDER_ID, SERVICE_NAME, SERVICE_KEY, MODEL_NAME, MODEL_VERSION, MODEL_TYPE, MODEL_TAGS, MODEL_DESCRIPTION, MODEL_DEPLOY_TYPE, DOCUMENT_URL, MODEL_SIZE, CONTEXT_LENGTH, MODEL_PRIORITY, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, API_URL, IS_REASONING, IS_SUPPORT_FUNCTION, INTERFACE_PROTOCOL, IS_SUPPORT_STREAM, AUTH_METADATA_ID, PUBLISH_STATUS, IDENTITY_ID, SYSTEM_PROMPT, THROTTLING_POLICY)
VALUES ('m1', 'model_test_provider', 'agentBuilder-128k', 'integration:default:agentBuilder-nlp-n2-reasoner-128k', 'agentBuilder-128k', 'agentBuilder-128k', 'LLM', NULL, '', 'PRIVATE-INTEGRATION', '', NULL, NULL, 500, '0', 'test_project_id', 'default', '2', '2', 1754668710605, 1754900088048, '', NULL, 1, 'STANDARD', 1, 'model_test_provider_mm', 'offline', 'bdf24b59', NULL, -1);

INSERT  INTO t_model_service (ID, PROVIDER_ID, SERVICE_NAME, SERVICE_KEY, MODEL_NAME, MODEL_VERSION, MODEL_TYPE, MODEL_TAGS, MODEL_DESCRIPTION, MODEL_DEPLOY_TYPE, DOCUMENT_URL, MODEL_SIZE, CONTEXT_LENGTH, MODEL_PRIORITY, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, API_URL, IS_REASONING, IS_SUPPORT_FUNCTION, INTERFACE_PROTOCOL, IS_SUPPORT_STREAM, AUTH_METADATA_ID, PUBLISH_STATUS, IDENTITY_ID, SYSTEM_PROMPT, THROTTLING_POLICY)
VALUES ('m2', 'model_test_provider', 'agentBuilder-128k2', 'integration:default:agentBuilder-nlp-n2-reasoner-128k2', 'agentBuilder-128k', 'agentBuilder-128k', 'LLM', NULL, '', 'PRIVATE-INTEGRATION', '', NULL, NULL, 500, '0', 'test_project_id', 'default', '2', '2', 1754668710605, 1754900088048, '', NULL, 1, 'STANDARD', 1, 'model_test_provider_mm', 'online', 'bdf24b59', NULL, -1);

INSERT  INTO t_model_service (ID, PROVIDER_ID, SERVICE_NAME, SERVICE_KEY, MODEL_NAME, MODEL_VERSION, MODEL_TYPE, MODEL_TAGS, MODEL_DESCRIPTION, MODEL_DEPLOY_TYPE, DOCUMENT_URL, MODEL_SIZE, CONTEXT_LENGTH, MODEL_PRIORITY, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, API_URL, IS_REASONING, IS_SUPPORT_FUNCTION, INTERFACE_PROTOCOL, IS_SUPPORT_STREAM, AUTH_METADATA_ID, PUBLISH_STATUS, IDENTITY_ID, SYSTEM_PROMPT, THROTTLING_POLICY)
VALUES ('test_deployment_id1', 'model_test_provider', 'agentBuilder-128k3', 'integration:default:agentBuilder-nlp-n2-reasoner-128k3', 'agentBuilder-128k', 'agentBuilder-128k', 'LLM', NULL, '', 'PRIVATE-INTEGRATION', '', NULL, NULL, 500, '0', 'test_project_id', 'default', '2', '2', 1754668710605, 1754900088048, '', NULL, 1, 'STANDARD', 1, 'model_test_provider_mm', 'online', 'bdf24b59', NULL, -1);


INSERT  INTO t_model_service (ID, PROVIDER_ID, SERVICE_NAME, SERVICE_KEY, MODEL_NAME, MODEL_VERSION, MODEL_TYPE, MODEL_TAGS, MODEL_DESCRIPTION, MODEL_DEPLOY_TYPE, DOCUMENT_URL, MODEL_SIZE, CONTEXT_LENGTH, MODEL_PRIORITY, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, API_URL, IS_REASONING, IS_SUPPORT_FUNCTION, INTERFACE_PROTOCOL, IS_SUPPORT_STREAM, AUTH_METADATA_ID, PUBLISH_STATUS, IDENTITY_ID, SYSTEM_PROMPT, THROTTLING_POLICY)
VALUES ('m3', '101', 'agentBuilder-128k', 'integration:default:agentBuilder-nlp-n2-reasoner-128k', 'agentBuilder-128k', 'agentBuilder-128k', 'LLM', NULL, '', 'PRIVATE-INTEGRATION', '', NULL, NULL, 500, '0', 'test_project_id', 'default', '2', '2', 1754668710605, 1754900088048, '', NULL, 1, 'STANDARD', 1, 'model_test_provider_mm', 'offline', 'bdf24b59', NULL, -1);

INSERT  INTO t_user_model_service_provider (ID, PROVIDER_NAME, PROVIDER_NAME_EN, DESCRIPTION, TAGS, PROVIDER_URL, CREATED_DATE, LAST_UPDATED_DATE, LOGO, STATUS, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, IDENTITY_ID)
 VALUES ('public_provider', 'public_provider', 'public_provider', '', NULL, '', 1754668644437, 1754668644437, 'data:image=', 'created', '0', 'other_project', 'default', '2', '2', 'model_test_provider');
INSERT  INTO t_provider_auth_metadata (ID, PROVIDER_ID, AUTH_TYPE, AUTH_INFO, AUTH_URL, CREATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, IDENTITY_ID)
VALUES ('public_provider_mm', 'public_provider', 'API_KEY', '{"API Key":""}', '', '2', 1754668644437, 1754668644437, '0', 'other_project', 'default', '070ad379');

INSERT  INTO t_provider_auth_info (ID, PROVIDER_ID, AUTH_METADATA_ID, AUTH_TYPE, AUTH_INFO, CREATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, IDENTITY_ID)
VALUES ('public_provider_aa', 'public_provider', 'public_provider_mm', 'NO_AUTH', '{}', '2', 1754964550955, 1754964550955, '0', 'other_project', 'default', 'df1a716a');

INSERT  INTO t_model_service (ID, PROVIDER_ID, SERVICE_NAME, SERVICE_KEY, MODEL_NAME, MODEL_VERSION, MODEL_TYPE, MODEL_TAGS, MODEL_DESCRIPTION, MODEL_DEPLOY_TYPE, DOCUMENT_URL, MODEL_SIZE, CONTEXT_LENGTH, MODEL_PRIORITY, DOMAIN_ID, PROJECT_ID, WORKSPACE_ID, CREATED_BY_USER, LAST_UPDATED_BY_USER, CREATED_DATE, LAST_UPDATED_DATE, API_URL, IS_REASONING, IS_SUPPORT_FUNCTION, INTERFACE_PROTOCOL, IS_SUPPORT_STREAM, AUTH_METADATA_ID, PUBLISH_STATUS, IDENTITY_ID, SYSTEM_PROMPT, THROTTLING_POLICY,IS_PUBLIC)
VALUES ('test_deployment_id2', 'public_provider', 'agentBuilder-128k', 'integration:public:agentBuilder-nlp-n2-reasoner-128k', 'agentBuilder-128k', 'agentBuilder-128k', 'LLM', NULL, '', 'PRIVATE-INTEGRATION', '', NULL, NULL, 500, '0', 'other_project', 'default', '2', '2', 1754668710605, 1754900088048, '', NULL, 1, 'STANDARD', 1, 'public_provider_mm', 'online', 'bdf24b59', NULL, -1, 1);
