#
# Copyright (c) Huawei Technologies Co., Ltd. 2026-2026. All rights reserved.
#
log.filter.newline.replace.list=\\n#\\r#\\f#\\b#\\u007F#\\u000B#\\t
ac.sensitive.field.list.regexp=(password|pass){20}(token){10000}