swagger: '2.0'
info:
  version: v1
  title: ros 相关 API
  description: Ros相关接口
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: Ros
    description: Ros相关接口
paths:
  /v1/agent-manager/{module_name}/cleannotify:
    post:
      tags:
        - RosCleanResource
      summary: 数据清理
      description: 数据清理通知接口
      operationId: cleanNotify
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: module_name
          in: path
          required: true
          type: string
          pattern: ^[a-zA-Z0-9_-]{1,40}$
          description: 模块名
        - name: notifyReq
          in: body
          required: true
          schema:
            $ref: '#/definitions/NotifyReq'
      responses:
        '200':
          description: 清理结果
          schema:
            $ref: '#/definitions/NotifyResp'
      x-order: 0

definitions:
  NotifyReq:
    type: object
    properties:
      domain_id:
        type: string
        maxLength: 64
        minLength: 2
        pattern: ^[a-zA-Z0-9_()\-]{1,40}$
      task_id:
        type: string
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]{1,40}$
  NotifyResp:
    type: object
    properties:
      res_code:
        type: string
        maxLength: 64
      res_msg:
        type: string
        maxLength: 64
      result:
        type: string
        maxLength: 64
      status:
        type: string
        maxLength: 64
      module_name:
        type: string
        maxLength: 64