swagger: '2.0'
info:
  version: v1
  title: 资源跨空间共享管理API
  description: 用于管理资源跨空间共享发布、查询、获取列表、删除等操作
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: ShareResourceManager

paths:
  /v1/{project_id}/agent-manager/resource/share:
    post:
      tags:
        - ShareResourceManager
      description: 资源（智能体、工作流、插件等）共享到其他空间
      operationId: createOrUpdateShareResource
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
        - name: shareResourceVo
          in: body
          required: true
          schema:
            $ref: '#/definitions/ShareResourceRequestInfo'
          description: 创建资源共享请求体
      responses:
        '200':
          description: 是否共享成功
          schema:
            type: boolean
            example: true
        '400':
          description: 共享资源失败
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

    get:
      tags:
        - ShareResourceManager
      description: 获取共享给当前空间的资源
      operationId: queryShareResourceList
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
        - name: resource_type
          in: query
          required: true
          type: string
          description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
          enum:
            - controller
            - workflow
            - plugin
        - name: offset
          in: query
          type: integer
          description: 分页记录的起始位置偏移量,默认值0
          default: 0
          minimum: 0
          maximum: 10000
        - name: limit
          in: query
          type: integer
          description: 每一页的数量,默认10
          default: 10
          minimum: 1
          maximum: 1000
        - name: resource_name
          in: query
          required: false
          type: string
      responses:
        '200':
          description: 跨空间共享对象对应的资源详情
          schema:
            $ref: '#/definitions/ShareResourceListRsp'
        '400':
          description: 获取函数列表失败
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

  /v1/{project_id}/agent-manager/resource/shared:
    get:
      tags:
        - ShareResourceManager
      description: 获取共享给当前空间的资源
      operationId: querySharedResourceList
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
        - name: resource_type
          in: query
          required: true
          type: string
          description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
          enum:
            - controller
            - workflow
            - plugin
        - name: resource_name
          in: query
          type: string
          description: 资源名称
          maxLength: 64
        - name: offset
          in: query
          type: integer
          description: 分页记录的起始位置偏移量,默认值0
          default: 0
          minimum: 0
          maximum: 10000
        - name: limit
          in: query
          type: integer
          description: 每一页的数量,默认10
          default: 10
          minimum: 1
          maximum: 1000
      responses:
        '200':
          description: 跨空间共享对象对应的资源详情
          schema:
            $ref: '#/definitions/ShareResourceListRsp'
        '400':
          description: 获取函数列表失败
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

  /v1/{project_id}/agent-manager/resource/share/{resource_id}:
    get:
      tags:
        - ShareResourceManager
      description: 查询跨空间共享对象记录信息，更新发布跨空间共享时，需要先加载已有的共享信息
      operationId: queryShareResourceInfoByResourceId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: resource_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 资源id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
        - name: release_version
          in: query
          required: true
          type: string
          description: 发布版本
        - name: resource_type
          in: query
          required: false
          type: string
          description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
          enum:
            - controller
            - workflow
            - plugin
      responses:
        '200':
          description: 资源共享记录详情
          schema:
            $ref: '#/definitions/ShareResourceResp'
        '400':
          description: 查询资源共享记录详情失败
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

    delete:
      tags:
        - ShareResourceManager
      description: 取消资源跨空间共享
      operationId: cancelShareResource
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: resource_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 资源id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
        - name: resource_type
          in: query
          required: false
          type: string
          description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
          enum:
            - controller
            - workflow
            - plugin
      responses:
        '200':
          description: 取消资源跨空间共享是否成功
          schema:
            type: boolean
        '400':
          description: 取消资源跨空间共享失败
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

definitions:
  ShareResourceRequestInfo:
    type: object
    required:
      - resource_id
      - resource_name
      - resource_type
      - version_list
      - auth_workspace_id_list
    properties:
      resource_id:
        type: string
        maxLength: 64
        description: 资源元素ID，资源唯一表示，如workflow_id
        pattern: ^[a-zA-Z0-9_-]+$
      resource_name:
        type: string
        description: 资源名称
        minLength: 1
        maxLength: 64
      resource_type:
        type: string
        description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
        enum:
          - controller
          - workflow
          - plugin
          - mcp
          - prompt
      version_list:
        type: array
        items:
          type: string
        maxLength: 64
        description: 被共享的版本列表（版本ID）
        minItems: 0
        maxItems: 50
      auth_workspace_id_list:
        type: array
        items:
          type: string
        maxLength: 64
        description: 授权空间列表（空间ID），特殊情况：all表示共享给所有空间，包括后续创建的空间
        minItems: 1
        maxItems: 1000
  ShareResourceResp:
    type: object
    properties:
      resource_id:
        type: string
        maxLength: 64
        description: 资源元素ID，资源唯一表示，如workflow_id
        pattern: ^[a-zA-Z0-9_-]+$
      resource_name:
        type: string
        maxLength: 64
        description: 资源名称
      resource_type:
        type: string
        description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
      resource_description:
        type: string
        description: 资源信息描述
      version_info_list:
        type: array
        items:
          $ref: '#/definitions/ResourceVersionInfo'
        description: 被共享的版本信息列表（包含版本ID和版本号）
        minItems: 1
        maxItems: 50
      resource_workspace_id:
        type: string
        description: 资源所属的空间ID
      resource_workspace_name:
        type: string
        description: 资源所属的空间名称
      workspace_list:
        type: array
        items:
          $ref: '#/definitions/AuthWorkspaceInfo'
        description: 资源授权空间列表
        minItems: 1
        maxItems: 100
      project_id:
        type: string
        maxLength: 64
        description: 租户项目id
        pattern: ^[a-zA-Z0-9_-]+$
      tenant_id:
        type: string
        maxLength: 64
        description: 租户id
        pattern: ^[a-zA-Z0-9_-]+$
      creator:
        type: string
        description: 创建人
      creator_id:
        type: string
        description: 创建人ID
      share_time:
        type: string
        format: date-time
        example: 1698984975
        description: 共享时间
      icon:
        type: string
        description: 图标
      agent_inputs:
        type: array
        items:
          $ref: '#/definitions/WorkflowFieldVO'
        description: 节点输入配置
      workflow_inputs:
        type: array
        items:
          $ref: '#/definitions/WorkflowFieldVO'
        description: 节点输入配置
      controller_inputs:
        type: array
        items:
          $ref: '#/definitions/WorkflowFieldVO'
  ShareResourceListRsp:
    type: object
    properties:
      count:
        type: integer
        description: 总数
      resource_list:
        type: array
        items:
          $ref: '#/definitions/ShareResourceInfo'
        description: 资源基本信息
  ShareResourceInfo:
    type: object
    properties:
      resource_id:
        type: string
        required: true
        maxLength: 64
        description: 资源元素ID，资源唯一表示，如workflow_id
        pattern: ^[a-zA-Z0-9_-]+$
      resource_type:
        type: string
        required: true
        description: 资源类型，controller-多智能体、workflow-工作流、plugin-插件
        enum:
          - controller
          - workflow
          - plugin
          - mcp
          - prompt
      version_info_list:
        type: array
        items:
          $ref: '#/definitions/ResourceVersionInfo'
        description: 被共享的版本信息列表（包含版本ID和版本号）
        required: true
        minItems: 1
        maxItems: 50
      workspace_id:
        type: string
        description: 资源所属空间ID
        maxLength: 64
        pattern: ^[a-zA-Z0-9_-]+$
      workspace_name:
        type: string
        description: 资源所属空间名称
        maxLength: 64
      resource_name_ch:
        type: string
        description: 资源中文名称
        maxLength: 128
      resource_name_en:
        type: string
        description: 资源英文名称
        maxLength: 128
      resource_desc:
        type: string
        description: 资源描述
        maxLength: 256
      resource_icon:
        type: string
        description: 资源图标
      creator:
        type: string
        description: 创建者
      type:
        type: string
        description: 资源类型，任务型工作流/对话型工作流
      extend_attribute:
        type: object
        additionalProperties:
          type: object
        description: 资源补充信息
  ResourceVersionInfo:
    type: object
    properties:
      version_id:
        type: string
        description: 版本ID
      version_name:
        type: string
        description: 版本号
  AuthWorkspaceInfo:
     type: object
     properties:
       workspace_id:
         type: string
         description: 版本ID
       workspace_name:
         type: string
         description: 版本号
  WorkflowFieldVO:
    type: object
    description: 工作流通用字段定义，用于inputs,outputs,condition
    properties:
      name:
        type: string
        description: 字段名
      cn_name:
        type: string
        description: 中文名称
      type:
        type: string
        description: 字段数据类型
      description:
        type: string
        description: 字段描述
      required:
        type: boolean
        description: 是否必填
      source:
        type: string
        default: user
        description: 字段数据来源
        enum:
          - system
          - user
          - pre_defined
      schema:
        type: object
        description: 字段schema
      aging_level:
        type: string
        description: 记忆变量时长
      storage_method:
        type: string
        description: 记忆变量存储方式
      field_type:
        type: string
        description: 字段输入框类型
      reflection:
        type: boolean
        description: 为每个参数增加是否进行反思的开关，默认关闭
        default: false
      value:
        type: object
        description: 字段取值
        properties:
          type:
            type: string
            description: 取值类型
            enum:
              - generated
              - ref
              - literal
              - nested
          content:
            type: object
            description: "取值结构如下：\ntype：generated， content=null\ntype：ref ，content为对象\n\tref_node_id：引用节点\n\tref_var_name：引用变量名\ntype：literal，content为字符"
          operator:
            type: string
            description: 运算符类型：increment-递增，decrement-递减，empty-null，empty_str-空字符，empty_arr-空列表。
            enum:
              - increment
              - decrement
              - empty
              - empty_str
              - empty_arr
          hint:
            type: string
            description: 字段值提示
          default:
            type: object
            description: 默认值
          display:
            type: object
            description: 前端显示值
      validator:
        type: array
        items:
          properties:
            type:
              type: string
              description: 校验器类型
            params:
              type: array
              items:
                type: string
              description: 校验器参数
        description: 校验器列表
      memory:
        type: array
        description: 字段相关的内存信息或状态
        items:
          type: object
          required:
            - name
          properties:
            name:
              type: string
              description: 记忆变量名称
            aging_level:
              type: string
              description: 记忆变量时长
            storage_method:
              type: string
              description: 记忆变量存储方式
            default_value:
              type: object
              description: 记忆变量的默认值
            description:
              type: string
              description: 记忆变量的描述
            value:
              type: object
              description: 字段取值
              properties:
                type:
                  type: string
                  description: 取值类型
                  enum:
                    - generated
                    - ref
                    - literal
                    - nested
                content:
                  type: object
                  description: "取值结构如下：\ntype：generated， content=null\ntype：ref ，content为对象\n\tref_node_id：引用节点\n\tref_var_name：引用变量名\ntype：literal，content为字符"
                operator:
                  type: string
                  description: 运算符类型：increment-递增，decrement-递减，empty-null，empty_str-空字符，empty_arr-空列表。
                  enum:
                    - increment
                    - decrement
                    - empty
                    - empty_str
                    - empty_arr
                hint:
                  type: string
                  description: 字段值提示
                default:
                  type: object
                  description: 默认值
                display:
                  type: object
                  description: 前端显示值
