swagger: '2.0'
info:
  version: v1
  title: agent manager API
  description: agent manager API
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: TenantOpenApi
paths:
  /v1/open/developer/agent-manager/agents:
    get:
      tags:
        - TenantOpenApi
      summary: 获取agent列表
      description: 获取agent列表
      operationId: ListDeveloperAgents
      produces:
        - application/json
      parameters:
        - name: workspace_id
          in: query
          required: false
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
        - name: marker
          in: query
          required: false
          type: integer
          format: int32
          default: 0
          minimum: 0
          maximum: 10000
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          default: 100
          minimum: 1
          maximum: 1000
        - name: X-User-Info
          in: header
          required: true
          type: string
      responses:
        '200':
          description: 搜索的agent列表
          schema:
            $ref: '#/definitions/DeveloperAgentListRsp'
        '400':
          description: Bad Request 请求错误
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0
  /v1/open/developer/agent-manager/agents/exist/published:
    get:
      tags:
        - TenantOpenApi
      summary: 查询是否存在已发布的agent
      description: 查询是否存在已发布的agent
      operationId: existPublishedAgent
      produces:
        - application/json
      parameters:
        - name: domainId
          in: query
          required: true
          type: string
          description: 账号id
          maxLength: 256
          minLength: 1
        - name: publishedDate
          in: query
          required: true
          type: integer
          format: int64
          description: 发布时间
      responses:
        '200':
          description: 是否存在已发布的agent
          schema:
            type: boolean
        '400':
          description: Bad Request 请求错误
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 1
definitions:
  DeveloperAgentListRsp:
    type: object
    description: 开发者空间查询agent列表响应
    properties:
      data:
        description: agent列表
        type: array
        items:
          $ref: '#/definitions/DeveloperAgentInfo'
      page_info:
        description: 分页结果
        $ref: '#/definitions/DeveloperSpacePage'
  DeveloperSpacePage:
    type: object
    description: 开发者空间查询分页信息
    properties:
      next_marker:
        type: string
        description: 下一页标记，用于下次调用请求的入参中的marker使用，标识要翻到本次请求的下一页。如果是末页，此项为null
      previous_marker:
        type: string
        description: 前一页标记，用于下次调用请求的入参中的marker使用，标识要翻到本次请求的前一页。如果是首页，此项为null
      current_count:
        type: integer
        format: int32
        description: 当前页的元素实际个数，比如单页个数为10，元素总数为93，那前9页的current_count为10，末页为3
  DeveloperAgentInfo:
    type: object
    description: 开发者空间agent资产信息
    properties:
      name:
        type: string
        description: 名称
      asset_id:
        type: string
        description: 资产唯一id
      asset_type_name:
        type: string
        description: 资产类型名称
      asset_type_display_name:
        type: string
        description: 资产类型的国际化展示名
      description:
        type: string
        description: 资产描述
      created_by:
        type: string
        description: 创建人
      create_time:
        type: integer
        format: int64
        description: 创建时间
      updated_by:
        type: string
        description: 更新人
      update_time:
        type: integer
        format: int64
        description: 更新时间
      properties:
        type: object
        additionalProperties:
          type: object
        description: 额外属性