swagger: '2.0'
info:
  version: v1
  title: iam鉴权委托
  description: iam鉴权委托接口
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: IamAuthorizationManager

paths:
  /v1/{project_id}/doAuthorization:
    post:
      tags:
        - IamAuthorizationManager
      description: 最终租户授权给op账号
      operationId: doAuthorization
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
      responses:
        '200':
          description: 成功授权
          schema:
            $ref: '#/definitions/BaseResp'
        '400':
          description: 授权失败
          schema:
            $ref: '#/definitions/BaseResp'
      x-order: 0

  /v1/{project_id}/queryAuthorization:
    get:
      tags:
        - IamAuthorizationManager
      description: 查询授权接列表
      operationId: queryAuthorization
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 项目空间id
          pattern: ^[a-zA-Z0-9_()\-]+$
          maxLength: 64
          minLength: 1
      responses:
        '200':
          description: 授权列表
          schema:
            $ref: '#/definitions/BaseResp'
        '400':
          description: 获取授权接列表失败
          schema:
            $ref: '#/definitions/BaseResp'
      x-order: 0

definitions:
  BaseResp:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
      data:
        type: object
