swagger: '2.0'
info:
  version: v1
  title: Agent_Base_OpenAPI_Documentation
schemes:
  - https
basePath: /
tags:
  - name: OpenKnowledgeBase
    x-name: 知识库
    x-order: 2001
parameters:
  xAuthToken:
    name: X-Auth-Token
    in: header
    x-open-region-cloud: hws
    description: |-
      **参数解释**：
      用户Token。通过调用IAM服务获取用户Token接口获取（响应消息头中X-Subject-Token的值）。

      **约束限制**：
      不涉及。

      **取值范围**：
      不涉及。

      **默认取值**：
      不涉及。
    required: true
    type: string
  projectId:
    name: project_id
    in: path
    description: |-
      **参数解释**：
      当前租户项目ID。
      获取方法请参考[获取项目ID](agent-builder_06_0018.xml)。

      **约束限制**：
      不涉及。

      **取值范围**：
      由英文，数字，“-”，“_”组成，不超过64位字符。

      **默认取值**：
      不涉及。
    required: true
    type: string
    maxLength: 64
  knowledgeBaseId:
    name: knowledge_base_id
    in: path
    description: |-
      **参数解释**：
      知识库的ID。
      获取方式：
      1. 进入AgentBuilder智能体平台。
      2. 在左侧导航选择“开发中心 > 知识库”。
      3. 在知识库列表的“知识库ID”列，复制知识库ID。

      **约束限制**：
      必须为已创建且处于可用状态的知识库ID；不支持跨项目访问。

      **取值范围**：
      由英文、数字、“-”、“_”组成，长度不超过64位字符。

      **默认取值**：
      不涉及。
    required: true
    maxLength: 64
    type: string
paths:
  /v2/{project_id}/knowledge-bases/retrieve:
    post:
      tags:
        - OpenKnowledgeBase
      operationId: OpenBatchRetrieveKnowledgeBase
      summary: 知识库检索
      description: |-
        提供多知识库并行检索能力，支持语义、关键词、混合及FAQ四种检索模式，并允许自定义相似度阈值与返回结果数量，实现精准高效的信息匹配。

        **适用场景**：
        - 同时从多个知识库或文档集合中搜索相关内容。
        - 在预设的问答列表中快速定位最相关的答案（FAQ检索）。
        - 通过混合模式或调整阈值，兼顾搜索结果的准确性和全面性。
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/projectId'
        - in: body
          name: OpenBathKnowledgeBaseRetrievalReq
          description: 知识库检索请求体。
          required: true
          schema:
            $ref: '#/definitions/OpenBatchKnowledgeBaseRetrievalReq'
      responses:
        '200':
          description: 知识库检索结果。
          schema:
            $ref: '#/definitions/OpenBatchKnowledgeBaseRetrievalRsp'
          x-response-examples-1:
            application/json:
              total: 1
              retrieve_result_list:
                - file_id: 687c7914cbddcc8702cb6698f6230...
                  title: test
                  chunk_id: 840003a72d6f4325958920e52c5a9...
                  content: |-
                    测试检索召回内容。
                  similarity: 0.9785156
                  knowledge_base_id: "b56c5138-96e3-4630-8381-7846dfdbcdd5"
      x-request-examples-tags-1: hws
      x-request-examples-description-1: 知识库检索。
      x-request-examples-1:
        method: POST
        url: https://api.example.com/v2/{project_id}/knowledge-bases/retrieve
        headers:
          Content-Type: application/json
          X-Auth-Token: TEST-TOKEN******
        body:
          knowledge_base_ids:
            - bad2ef8771e6443096b528a8a7gh....
          query: 测试检索问题。
          search_mode: DOC
          top_k: 10
          similarity_threshold: 0.5
      x-request-examples-tags-2: stand_a
      x-request-examples-description-2: 知识库检索。
      x-request-examples-2:
        method: POST
        url: https://api.example.com/v2/{project_id}/knowledge-bases/retrieve
        headers:
          Content-Type: application/json
        body:
          knowledge_base_ids:
            - bad2ef8771e6443096b528a8a7gh....
          query: 测试检索问题。
          search_mode: DOC
          top_k: 10
          similarity_threshold: 0.5
      x-order: 1
      x-iam-auth-meta-anno:
        abacAction: ''
        authLevel: PROJECT
        needAbacCheck: false
        needRbacCheck: false
        needCbcCheck: false
        model: v3
  /v1/{project_id}/knowledge-bases/{knowledge_base_id}/retrieve:
    post:
      tags:
        - OpenKnowledgeBase
      summary: 知识库检索（v1.5）
      description: |-
        适配知识库1.5接口，可根据知识库ID进行知识库检索。

        **适用场景**：
        - 必须使用内置RAGFlow知识库。
        - 仅支持FAQ场景（适配知识库1.5检索接口切片提取问答）。
      operationId: OpenRetrieveKnowledgeBase
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/projectId'
        - $ref: '#/parameters/knowledgeBaseId'
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/OpenKnowledgeBaseRetrievalReq'
      responses:
        '200':
          description: 知识库检索结果。
          schema:
            $ref: '#/definitions/OpenKnowledgeBaseRetrievalRsp'
          x-response-examples-1:
            application/json:
              data:
                - document: |-
                    测试检索召回内容。
                  chunk_fragments: null
                  similarity: 0.9765625
      x-request-examples-tags-1: hcs
      x-request-examples-description-1: 知识库检索（v1.5）。
      x-request-examples-1:
        method: POST
        url: https://api.example.com/v1/{project_id}/knowledge-bases/{knowledge_base_id}/retrieve
        headers:
          Content-Type: application/json
          X-Auth-Token: TEST-TOKEN******
        body:
          similarity_min: 0.9
          limit: 5
          keyword: 测试检索问题。
      x-open-region-cloud: hcs
      x-order: 2
      x-iam-auth-meta-anno:
        abacAction: ''
        authLevel: PROJECT
        needAbacCheck: false
        needRbacCheck: false
        needCbcCheck: false
        model: v3
  /v2/{project_id}/knowledge-bases/{knowledge_base_id}/files/{file_id}/content:
    get:
      tags:
        - OpenKnowledgeBase
      summary: 文件下载。
      description: |-
        下载知识库中的指定文件。
        - 注意： 文件的默认有效期为7天。
      operationId: OpenDownloadFile
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目。
          minLength: 1
        - name: knowledge_base_id
          in: path
          required: true
          type: string
          description: 知识库ID。
          minLength: 1
          maxLength: 100
        - name: file_id
          in: path
          required: true
          type: string
          description: 文件ID。
          minLength: 1
          maxLength: 100
      responses:
        '200':
          description: 文件流。
          schema:
            type: file
      x-order: 3
      x-iam-auth-meta-anno:
        abacAction: ''
        authLevel: PROJECT
        needAbacCheck: false
        needRbacCheck: false
        needCbcCheck: false
        model:
          v3:
definitions:
  OpenKnowledgeBaseRetrievalReq:
    description: 知识检索请求体。
    type: object
    required:
      - limit
      - keyword
    properties:
      similarity_min:
        type: number
        format: float
        default: 0.5
        example: 0.78
        description: |-
          **参数解释**：
          检索结果的最小相似度阈值，用于过滤低相关性片段。

          **约束限制**：
          不涉及。

          **取值范围**：
          [0.0, 1.0]，包含两端。

          **默认取值**：
          0.5。
        minimum: 0
        maximum: 1
      limit:
        type: integer
        format: int32
        example: 10
        default: 10
        description: |-
          **参数解释**：
          指定返回的检索结果最大数量。

          **约束限制**：
          必须为正整数，且不超过系统最大返回限制。

          **取值范围**：
          1 至 100（含）。

          **默认取值**：
          10。
        maximum: 100
        minimum: 1
      keyword:
        type: string
        example: 测试检索问题。
        minLength: 1
        maxLength: 4096
        description: |-
          **参数解释**：
          用户输入的检索关键字。

          **约束限制**：
          不涉及。

          **取值范围**：
          不涉及。

          **默认取值**：
          不涉及。
  OpenKnowledgeBaseRetrievalRsp:
    description: 知识检索响应体。
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ChunkData'
  ChunkData:
    description: |-
      **参数解释**：
      切片明细。

      **取值范围**：
      不涉及。
    type: object
    properties:
      document:
        type: string
        example: |-
          测试检索召回内容。
        description: |-
          **参数解释**：
          检索命中的文本内容片段。

          **取值范围**：
          不涉及。
      chunk_fragments:
        type: object
        example: |-
          {answer: 测试检索召回内容。}
        description: |-
          **参数解释**：
           切片片段，应用于FAQ场景。

          **取值范围**：
          不涉及。
        additionalProperties:
          type: string
      similarity:
        type: number
        format: float
        example: 0.87
        description: |-
          **参数解释**：
          检索字段（document）和用户检索关键字（keyword）的相似度。

          **取值范围**：
          不涉及。
  OpenBatchKnowledgeBaseRetrievalReq:
    type: object
    description: 知识检索请求体。
    required:
      - knowledge_base_ids
      - query
    properties:
      knowledge_base_ids:
        type: array
        description: |-
          **参数解释**：
          知识库ID列表。

          **约束限制**：
          最多可同时检索3个知识库。

          **取值范围**：
          不涉及。

          **默认取值**：
          不涉及。
        minItems: 1
        maxItems: 3
        items:
          type: string
          description: 知识库ID。
          minLength: 0
          maxLength: 100
        example:
          - 781d380d-ac06-11f0-8c32-fa163ea89...
          - 82e8dda0-ac06-11f0-8c32-fa163ea89...
      query:
        type: string
        description: |-
          **参数解释**：
          用户输入的问题或关键词。

          **约束限制**：
          不涉及。

          **取值范围**：
          长度 1 至 4096 字符。

          **默认取值**：
          不涉及。
        example: 测试检索问题。
        minLength: 1
        maxLength: 4096
      search_mode:
        type: string
        description: |-
          **参数解释**：
          检索策略模式。

          **约束限制**：
          不涉及。

          **取值范围**：
          - doc：语义检索。
          - keyword：关键词检索。
          - mix：混合检索。
          - faq：FAQ检索。

          **默认取值**：
          doc。
        default: doc
        minLength: 1
        maxLength: 16
        enum:
          - doc
          - keyword
          - mix
          - faq
      top_k:
        type: integer
        description: |-
          **参数解释**：
          每个知识库最多返回的检索结果数量。

          **约束限制**：
          若传入小数，系统会默认截断小数部分。

          **取值范围**：
          1 至 100（含）。

          **默认取值**：
          10。
        format: int32
        default: 10
        minimum: 1
        maximum: 100
      similarity_threshold:
        description: |-
          **参数解释**：
          检索结果的最低相关度得分，低于此值的片段将被过滤。

          **约束限制**：
          不涉及。

          **取值范围**：
          [0.0, 1.0]，包含两端。

          **默认取值**：
          0.5。
        type: number
        format: float
        default: 0.5
        minimum: 0
        maximum: 1
      image_mask_policy:
        type: string
        description: |-
          **参数解释**：
          知识检索结果切片中，对图片标签进行处理和保留的具体方式。

          **约束限制**：
          该功能要求被检索的知识库本身支持返回图片信息。

          **取值范围**：
          - RETAIN_IMAGE_ID：保留图片ID，格式：{KI|imageId}。
          - RETAIN_PLACEHOLDER：保留占位符，格式：{KI|N}，N为序号。
          - REMOVE_IMAGE：移除图片（即替换为空字符串）。

          **默认取值**：
          REMOVE_IMAGE。
        default: REMOVE_IMAGE
        minLength: 1
        maxLength: 64
        enum:
          - RETAIN_IMAGE_ID
          - RETAIN_PLACEHOLDER
          - REMOVE_IMAGE
  OpenBatchKnowledgeBaseRetrievalRsp:
    type: object
    description: 知识检索响应体。
    required:
      - total
    properties:
      total:
        type: integer
        format: int32
        description: |-
          **参数解释**：
          检索结果总数。

          **取值范围**：
          不涉及。
        maximum: 65535
      retrieve_result_list:
        type: array
        description: |-
          **参数解释**：
          检索结果列表。

          **取值范围**：
          不涉及。
        items:
          $ref: '#/definitions/RetrievalResultInfo'
  RetrievalResultInfo:
    type: object
    description: 检索结果。
    properties:
      file_id:
        type: string
        description: |-
          **参数解释**：
          文件ID（或FAQ ID）。

          **取值范围**：
          不涉及。
        minLength: 1
        maxLength: 64
      title:
        type: string
        description: |-
          **参数解释**：
          文档标题（如果是FAQ，返回QUESTION）。

          **取值范围**：
          不涉及。
      chunk_id:
        type: string
        description: |-
          **参数解释**：
          分片ID。

          **取值范围**：
          不涉及。
        pattern: ^[a-zA-Z0-9_-]+$
        minLength: 1
        maxLength: 64
      content:
        type: string
        description: |-
          **参数解释**：
          文本内容（如果是FAQ，返回ANSWER）。

          **取值范围**：
          不涉及。
        minLength: 1
        maxLength: 65535
      similarity:
        type: number
        format: float
        description: |-
          **参数解释**：
          相似度。

          **取值范围**：
          [0.0, 1.0]，包含两端。
      knowledge_base_id:
        type: string
        description: |-
          **参数解释**：
          知识库ID。

          **取值范围**：
          不涉及。
        minLength: 1
        maxLength: 64
      image_ids:
        type: array
        description: |-
          **参数解释**：
          检索到的图片列表（需知识库支持），与content中的图片占位符{KI|N}保持一一对应关系，N为图片索引值，从0开始。

          **取值范围**：
          不涉及。
        items:
          type: string
          description: 图片ID。
  ErrorRsp:
    type: object
    description: 完整错误信息。
    properties:
      error_code:
        type: string
        description: 错误码。
      error_msg:
        type: string
        description: 错误信息。
      details:
        type: array
        items:
          $ref: '#/definitions/ErrorDetail'
        description: 调用接口返回的错误信息。
  ErrorDetail:
    type: object
    description: 错误信息。
    properties:
      error_code:
        type: string
        description: 错误码。
      error_msg:
        type: string
        description: 错误信息。