swagger: '2.0'
info:
  version: v1
  title: agent manager API
  description: agent manager API
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: Workspace
paths:
  /v1/{project_id}/agent-manager/workspace:
    get:
      tags:
        - Workspace
      description: 查询团队空间列表。
      operationId: queryWorkspace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          description: 项目ID。
        - name: scope
          in: query
          required: false
          type: string
          description: 查询范围，user-查询用户下有哪些空间，project-查询当前project下有哪些空间。
          enum:
            - user
            - project
            - domain
          default: user
        - name: type
          in: query
          required: false
          type: string
          description: PERSON-个人空间，TEAM-团队空间。
          enum:
            - PERSON
            - TEAM
        - name: source
          in: query
          required: false
          type: string
          description: 用户来源，例如IAM。
      responses:
        '200':
          description: 获取团队空间列表响应体。
          schema:
            $ref: '#/definitions/GetWorkspaceListRsp'
        '400':
          description: 请求参数错误。
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

    post:
      tags:
        - Workspace
      description: 创建团队空间。
      operationId: CreateWorkspace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          description: 项目ID。
          type: string
        - name: create_workspace_req
          in: body
          required: true
          description: 创建团队空间请求体。
          schema:
            $ref: '#/definitions/CreateWorkspaceReq'
      responses:
        '200':
          description: 是否创建成功。
          schema:
            type: string
            description: 工作空间ID。
            example: 321321321
        '400':
          description: 请求参数错误。
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

    put:
      tags:
        - Workspace
      description: 修改工作空间。
      operationId: UpdateWorkspace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          description: 项目ID。
          type: string
        - name: update_workspace_req
          in: body
          required: true
          description: 更新团队空间请求体。
          schema:
            $ref: '#/definitions/UpdateWorkspaceReq'
      responses:
        '200':
          description: 是否更新成功。
          schema:
            $ref: '#/definitions/WorkspaceInfo'
        '400':
          description: 请求参数错误。
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

    delete:
      tags:
        - Workspace
      description: 删除团队空间。
      operationId: DeleteWorkspace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          description: 项目ID。
        - name: delete_workspace_req
          in: body
          required: true
          description: 删除团队空间请求体。
          schema:
            $ref: '#/definitions/DeleteWorkspaceReq'
      responses:
        '200':
          description: 删除成功。
          schema:
            type: string
            example: true
        '400':
          description: 请求参数错误。
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

  /v1/{project_id}/agent-manager/workspace/{workspace_id}:
    get:
      tags:
        - Workspace
      description: 查询指定ID的空间信息。
      operationId: QueryWorkspaceById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          description: 项目ID。
          type: string
        - name: workspace_id
          in: path
          required: true
          description: 空间ID。
          type: string
      responses:
        '200':
          description: 获取团队空间详情。
          schema:
            $ref: '#/definitions/WorkspaceInfo'
        '400':
          description: 请求参数错误。
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

  /v1/{project_id}/agent-manager/workspace/init:
    post:
      tags:
        - Workspace
      description: 用户空间初始化，如果用户没有个人空间，给用户创建个人空间，初始化后返回用户所在的空间列表。
      operationId: InitWorkspace
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          description: 项目ID。
        - name: scope
          in: query
          required: false
          type: string
          description: user-查询用户下有哪些空间，project-查询当前project下有哪些空间。
          enum:
            - user
            - project
          default: user
      responses:
        '200':
          description: 获取团队空间列表响应体。
          schema:
            $ref: '#/definitions/GetWorkspaceListRsp'
        '400':
          description: 请求参数错误。
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

definitions:
  GetWorkspaceListRsp:
    type: object
    description: 获取团队空间列表。
    properties:
      count:
        type: integer
        format: int32
        description: 总数
      workspaceList:
        type: array
        items:
          $ref: '#/definitions/WorkspaceInfo'
        description: 工作空间列表。
  CommonWorkspaceReq:
    type: object
    description: 创建工作空间请求体。
    properties:
      id:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 空间ID。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]+$
      name:
        type: string
        example: 测试空间
        description: 团队空间名称。
        minLength: 1
        maxLength: 64
      icon:
        type: string
        description: 工作空间图标。
      description:
        type: string
        description: 描述。
      type:
        type: string
        description: 空间类型。
  WorkspaceInfo:
    type: object
    description: 团队空间描述信息。
    properties:
      id:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 空间ID。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]+$
      name:
        type: string
        example: 测试空间。
        description: 团队空间名称。
        minLength: 1
        maxLength: 64
        pattern: ^[\u4e00-\u9fa5a-zA-Z0-9\-_]+$
      projectId:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 项目ID。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_-]+$
      flag:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 工作空间标识。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_-]+$
      icon:
        type: string
        description: 工作空间图标。
      description:
        type: string
        description: 描述。
        maxLength: 256
      tenantId:
        type: string
        example: 123546
        description: 租户ID。
        minLength: 1
        maxLength: 128
        pattern: ^[a-zA-Z0-9_-]+$
      type:
        type: string
        example: PERSON、TEAM
        description: 团队空间类型。
        minLength: 1
        maxLength: 32
      status:
        type: string
        example: active、deleted
        description: 团队空间状态。
        minLength: 1
        maxLength: 64
      creator:
        type: string
        description: 团队空间创建者。
      creatorId:
        type: string
        example: 123546
        description: 创建用户ID。
        minLength: 1
        maxLength: 128
        pattern: ^[a-zA-Z0-9_-]+$
      createdOn:
        type: string
        format: date-time
        description: 创建时间。
      updater:
        type: string
        description: 团队空间更新者。
      updaterId:
        type: string
        example: 123546
        description: 更新用户ID。
        minLength: 1
        maxLength: 128
        pattern: ^[a-zA-Z0-9_-]+$
      updatedOn:
        type: string
        format: date-time
        description: 更新时间。
      role:
        type: string
        description: 所属空间角色。
      externalMappingInfo:
        type: array
        description: 扩展参数（JSON 或其他文本）。
        items:
          $ref: '#/definitions/ExternalMappingInfo'
  CreateWorkspaceReq:
    type: object
    description: 创建工作空间请求体。
    required:
      - name
    properties:
      id:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 空间ID。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]+$
      name:
        type: string
        pattern: "^[\\\\u4e00-\\\\u9fa5a-zA-Z0-9_\\\\-（）()！!](?:[\\\\u4e00-\\\\u9fa5a-zA-Z0-9_\\\\-（）()！! ]*[\\\\u4e00-\\\\u9fa5a-zA-Z0-9_\\\\-（）()！!])?$"
        example: 测试空间
        description: 团队空间名称。
        minLength: 1
        maxLength: 64
      icon:
        type: string
        description: 工作空间图标。
      description:
        type: string
        description: 描述。
        maxLength: 256
      type:
        type: string
        description: 空间类型。
      externalMappingInfo:
        $ref: '#/definitions/ExternalMappingInfo'
  UpdateWorkspaceReq:
    type: object
    description: 修改工作空间请求体。
    required:
      - id
      - name
    properties:
      id:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 空间ID。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]+$
      name:
        type: string
        pattern: "^[\\\\u4e00-\\\\u9fa5a-zA-Z0-9_\\\\-（）()！!](?:[\\\\u4e00-\\\\u9fa5a-zA-Z0-9_\\\\-（）()！! ]*[\\\\u4e00-\\\\u9fa5a-zA-Z0-9_\\\\-（）()！!])?$"
        example: 测试空间
        description: 团队空间名称。
        minLength: 1
        maxLength: 64
      icon:
        type: string
        description: 工作空间图标。
      description:
        type: string
        description: 描述。
        maxLength: 256
      externalMappingInfo:
        $ref: '#/definitions/ExternalMappingInfo'
  DeleteWorkspaceReq:
    type: object
    description: 删除工作空间请求体。
    required:
      - id
    properties:
      id:
        type: string
        example: 22104392-0535-48cc-a060-bd173199c5c3
        description: 空间ID。
        minLength: 1
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]+$
      externalMappingInfo:
        $ref: '#/definitions/ExternalMappingInfo'
  Extension:
    type: object
    description: 扩展参数。
    properties:
      key:
        type: string
        description: 扩展 key。
      value:
        type: string
        description: 扩展 value。
      secretLevel:
        $ref: '#/definitions/SecretLevel'
    required:
      - key
      - value
  SecretLevel:
    type: string
    description: 密级（None | Encryption）
    default: None
    enum:
      - None
      - Encryption
  WorkspaceMapping:
    type: object
    description: 工作空间外部映射表实体。
    properties:
      id:
        type: string
        description: 主键ID。
        maxLength: 64
      workspaceId:
        type: string
        description: 空间ID。
        maxLength: 64
      externalMappingId:
        type: string
        description: 外部映射ID。
        maxLength: 128
      externalExtension:
        type: string
        description: 扩展参数（JSON 或其他文本）。
      externalMappingSource:
        type: integer
        description: 外部映射来源。
  ExternalMappingInfo:
    type: object
    description: 和外部空间映射信息。
    properties:
      workspaceId:
        type: string
        description: 空间ID。
        maxLength: 64
      mappingId:
        type: string
        description: 外部映射ID。
        maxLength: 128
      extensionContent:
        type: array
        description: 扩展参数（JSON 或其他文本）。
        items:
          $ref: '#/definitions/Extension'
      source:
        type: string
        description: 外部映射来源。
