swagger: '2.0'
info:
  version: v1
  title: resource manager API
  description: resource manager API
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: ResourceManagement

paths:
  /v1/{project_id}/agent-manager/resource-management:
    get:
      tags:
        - ResourceManagement
      summary: 获取当前资源使用情况及是否超限
      description: 获取当前资源使用情况及是否超限
      operationId: resourceUsageDetails
      x-api-type: open-api
      x-support-sdk: 'N'
      x-is-registered: 'N'
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          maxLength: 64
          description: 租户项目id
          pattern: ^[a-zA-Z0-9_-]+$
        - name: resourceType
          in: query
          required: true
          type: string
          maxLength: 64
      responses:
        '200':
          description: 服务响应体
          schema:
            $ref: '#/definitions/ResourceUsageDetails'
        '400':
          description: Bad Request 请求错误
          schema:
            type: string
        '401':
          description: Unauthorized 鉴权失败
          schema:
            type: string
        '403':
          description: Forbidden 没有操作权限
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
        '404':
          description: Not Found 找不到资源
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
        '500':
          description: Internal Server Error 服务内部错误
          schema:
            $ref: 'AgentStudio-Manager-API.yaml#/definitions/ErrorRsp'
      x-order: 0

definitions:
  ResourceUsageDetails:
    type: object
    description: 资源使用详情
    properties:
      type:
        type: string
        description: 资源类型
      isExceedLimit:
        type: boolean
        description: 是否超出限额
        default: true
      usedLimit:
        type: integer
        description: 已经使用额度
        default: 0
      totalAmount:
        type: integer
        description: 总额度
        default: 0
