swagger: '2.0'
info:
  version: v1
  title: API Key Management API
  description: API Key 管理接口，用于创建、查询、删除和鉴权 API Key
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: ApiKeyMgmt
    description: API Key 管理相关接口

paths:
  /v1/{project_id}/api-auth/api-keys:
    post:
      tags:
        - ApiKeyMgmt
      summary: 创建 API Key
      description: 租户管理员通过该接口创建 API Key 并返回
      operationId: createApiKey
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          pattern: ^[a-zA-Z0-9_-]{1,40}$
        - name: workspace_id
          in: query
          required: true
          type: string
          pattern: ^[a-zA-Z0-9_()\-]{1,40}$
        - name: api_key_request
          in: body
          required: true
          schema:
            $ref: '#/definitions/ApiKeyRequest'
      responses:
        '200':
          description: 创建的apikey信息
          schema:
            $ref: '#/definitions/ApikeyResponse'

  /v1/{project_id}/api-auth/api-keys/list:
    get:
      tags:
        - ApiKeyMgmt
      summary: 查询 API Key 列表
      description: 租户管理员通过该接口查询当前租户的 API Key 列表
      operationId: queryApiKeys
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          pattern: ^[a-zA-Z0-9_-]{1,40}$
        - name: workspace_id
          in: query
          required: true
          type: string
          pattern: ^[a-zA-Z0-9_()\-]{1,40}$
        - name: page_size
          in: query
          type: integer
          format: int32
          required: false
          maximum: 1000
          minimum: 1
          default: 10
        - name: page_num
          in: query
          type: integer
          format: int32
          required: false
          default: 0
          minimum: 0
      responses:
        '200':
          description: 查询成功
          schema:
              $ref: '#/definitions/ApiKeysListResp'

  /v1/{project_id}/api-auth/api-keys/{id}:
    delete:
      tags:
        - ApiKeyMgmt
      summary: 删除 API Key
      description: 租户管理员通过该接口删除指定的 API Key 信息
      operationId: deleteApiKey
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: project_id
          in: path
          required: true
          type: string
        - name: workspace_id
          in: query
          required: true
          type: string
      responses:
        '200':
          description: 删除成功

definitions:
  ApiKeyRequest:
    type: object
    properties:
      apikey_name:
        type: string
        maxLength: 64
        pattern: '^[\u4e00-\u9fa5a-zA-Z][\u4e00-\u9fa5a-zA-Z0-9_.-]{1,35}$'
      apikey_description:
        type: string
        maxLength: 1024

  ApiKeys:
    type: object
    properties:
      api_key_id:
        type: string
      api_key_name:
        type: string
      description:
        type: string
      created_date:
        type: integer
        format: int64

  ApikeyResponse:
    type: object
    properties:
      id:
        type: string
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]{1,64}$
      apikey:
        type: string
        maxLength: 64
        pattern: ^[a-zA-Z0-9_()\-]{1,64}$

  ApiKeysListResp:
    type: object
    properties:
      total:
        type: integer
      data:
        type: array
        items:
          $ref: '#/definitions/ApiKeys'