swagger: '2.0'
info:
  description: API for managing custom connector actions.
  version: 1.0.0
  title: Custom PromptApi API
host: your.api.host
basePath: /
schemes:
  - http
  - https
paths:
  /v2/{project_id}/agent-builder/prompt/list:
    get:
      tags:
        - PromptApi
      summary: 查询单个自定义连接器的单个执行动作详细信息
      description: Get prompt list
      operationId: getPromptLists
      produces:
        - application/json
      parameters:
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 工作空间ID
        - name: project_id
          in: path
          required: true
          type: string
          description: 项目ID
        - name: limit
          in: query
          required: true
          type: integer
          default: 10
          minimum: 10
          maximum: 1000
        - name: offset
          in: query
          required: true
          type: integer
          minimum: 0
          maximum: 10000
        - name: name
          in: query
          type: string
          minLength: 0
          maxLength: 255
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/PePromptNewListVo'
  /v2/{project_id}/agent-builder/prompt:
    put:
      tags:
        - PromptApi
      summary: 更新提示词
      description: Update CustomPromptApi Action
      operationId: updateCustomPromptApiAction
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
          description: 项目ID
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 工作空间ID
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/PePromptTemplateNewVo'
      responses:
        200:
          description: 操作成功
          schema:
            $ref: '#/definitions/CreatePromptResp'
    post:
      tags:
        - PromptApi
      summary: 创建一个提示词
      description: Create CustomPromptApi Action
      operationId: createCustomPromptApiAction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
        - name: pe_prompt
          in: body
          required: true
          description: 创建或者更新候选模板请求体
          schema:
            $ref: '#/definitions/PePromptTemplateNewVo'
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 工作空间ID
      responses:
        '200':
          description: 操作成功
          schema:
            type: string
    get:
      tags:
        - PromptApi
      summary: 查询提示词详情
      description: Get CustomPromptApi Actions
      operationId: queryCustomPromptApiActions
      produces:
        - application/json
      parameters:
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 工作空间ID
        - name: project_id
          in: path
          required: true
          type: string
          description: 项目ID
        - name: prompt_id
          in: path
          required: true
          type: string
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
          description: ID of CustomPromptApi
        - name: name
          in: query
          required: false
          type: string
          description: 名称
      responses:
        200:
          description: 操作成功,返回CustomPromptApi执行动作列表
          schema:
            $ref: '#/definitions/PePromptTemplateNewVo'
  /v2/{project_id}/prompt/tasks/prompt/save:
    post:
      tags:
        - PromptApi
      summary: 保存模板
      description: Save Prompt Template
      operationId: SavePromptTemplate
      x-apigateway-request-type: Private
      x-is-registered: 'Y'
      x-support-sdk: 'Y'
      x-apiexplorer-hide: 'N'
      produces:
        - application/json
      parameters:
        - name: project_id
          in: path
          required: true
          type: string
        - name: workspace_id
          in: query
          required: true
          type: string
          description: 工作空间ID
        - name: pe_prompt_template
          in: body
          required: true
          description: 创建模板请求体
          schema:
            $ref: '#/definitions/PePromptTemplateNewVo'
      responses:
        200:
          description: 启动成功
          schema:
            $ref: '#/definitions/CreatePromptResp'
definitions:
  PePromptNewVo:
    type: object
    properties:
      id:
        type: string
        description: 模板id
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
      name:
        type: string
        description: 模板名称
        pattern: ^[\u4e00-\u9fa5a-zA-Z][\u4e00-\u9fa5\w-()（）]{0,32}[\u4e00-\u9fa5a-zA-Z0-9()（）]$
      content:
        type: string
        description: 模板内容
        minLength: 1
        maxLength: 10000
      creator:
        type: string
        description: 创建人
      updater:
        type: string
        description: 更新人
      created_on:
        type: string
        format: date-time
        description: 创建时间
      updated_on:
        type: string
        format: date-time
        description: 修改时间
  CreatePromptResp:
    type: object
    description: 提示词响应
    properties:
      code:
        type: integer
      message:
        type: string
      data:
        type: object
  PePromptNewDto:
    type: object
    description: 候选模板创建入参
    properties:
      name:
        type: string
        description: 模板名称
        minLength: 0
        maxLength: 256
        pattern: ^[\u4e00-\u9fa5a-zA-Z][\u4e00-\u9fa5\w-()（）]{0,32}[\u4e00-\u9fa5a-zA-Z0-9()（）]$
      content:
        type: string
        description: 人工打分
        minimum: 0
        maximum: 512
      description:
        type: string
        description: 人工打分
        minimum: 0
        maximum: 256
      creator:
        type: string
        description: 创建人
      updater:
        type: string
        description: 修改人
  PePromptNewListVo:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/PePromptTemplateNewVo'
      total_page:
        type: integer
        format: int32
        minimum: 1
      count:
        type: integer
        format: int64
      has_next_page:
        type: boolean
  PePromptTemplateNewVo:
    type: object
    description: 创建模板请求体
    required:
      - content
      - name
      - source
      - py_type
    properties:
      id:
        type: string
        pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      name:
        type: string
        pattern: ^[\u4e00-\u9fa5a-zA-Z][\u4e00-\u9fa5\w-()（）]{0,32}[\u4e00-\u9fa5a-zA-Z0-9()（）]$
      content:
        type: string
        minLength: 1
        maxLength: 10000
      creator:
        type: string
      created_on:
        type: string
      updated_on:
        type: string
      description:
        type: string
        minLength: 0
        maxLength: 255
      industry_id:
        type: string
        pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      source:
        type: string
        pattern: PLAYGROUND|EXPERIMENT|CANDIDATE|HORIZONTAL|NO_SOURCE|PRESET
      variables:
        type: string
        minLength: 0
      pt_type:
        type: string
        pattern: multi|text
      tags:
        type: array
        items:
          type: string

